"""knowledge base documents chunks and embeddings

Revision ID: 43cb018a3a35
Revises: be3cf5c03cd4
Created: 2026-08-10 13:03:27.800403

The HNSW indexes at the bottom are hand-written: Alembic cannot autogenerate
them, because they are *partial* indexes over a *casting expression*.

`chunk_embeddings.embedding` is an unconstrained `halfvec`, so that embedding
models of different dimensions can coexist over one corpus (plan D3 — the
embedding model is an experiment variable, and 768-dimension nomic-embed-text and
1536-dimension text-embedding-3-small must both be storable). pgvector cannot
index a column of unknown width, so each index fixes the width itself with a cast
and restricts itself to the rows of that width.

Keying the indexes on `embedding_dim` rather than on `embedding_model` means a new
model of an existing dimension needs no migration at all. Queries filter on both:
`embedding_dim` to hit the index, `embedding_model` for correctness.

Creating them empty is free; each one only grows if a model of that dimension is
actually used.
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "43cb018a3a35"
down_revision: str | None = "be3cf5c03cd4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Dimensions the shipped providers emit. 256 is the deterministic test double,
#: 768 nomic-embed-text, 1024 mxbai/bge-m3, 1536 text-embedding-3-small, 3072
#: text-embedding-3-large. halfvec supports HNSW up to 4000 dimensions, where
#: plain `vector` stops at 2000 — another reason the column is half precision.
INDEXED_DIMENSIONS: tuple[int, ...] = (256, 384, 768, 1024, 1536, 3072)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "PROCESSING",
                "READY",
                "FAILED",
                name="document_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("ingestion_ms", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_documents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("user_id", "sha256", name="uq_documents_user_id_sha256"),
        schema="app",
    )
    op.create_index("ix_documents_status", "documents", ["status"], unique=False, schema="app")
    op.create_index(
        "ix_documents_user_id_created_at",
        "documents",
        ["user_id", "created_at"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "document_chunks",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("page_from", sa.Integer(), nullable=True),
        sa.Column("page_to", sa.Integer(), nullable=True),
        sa.Column("section_path", sa.String(length=512), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=False,
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["app.documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        schema="app",
    )
    op.create_index(
        "ix_document_chunks_document_id_chunk_index",
        "document_chunks",
        ["document_id", "chunk_index"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_document_chunks_tsv",
        "document_chunks",
        ["tsv"],
        unique=False,
        schema="app",
        postgresql_using="gin",
    )
    op.create_table(
        "chunk_embeddings",
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("embedding_dim", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.HALFVEC(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["app.document_chunks.id"],
            name=op.f("fk_chunk_embeddings_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunk_embeddings")),
        sa.UniqueConstraint(
            "chunk_id", "embedding_model", name="uq_chunk_embeddings_chunk_id_model"
        ),
        schema="app",
    )
    # ### end Alembic commands ###

    # Supports the `embedding_model = ... AND embedding_dim = ...` filter that
    # every retrieval query applies before ordering by distance.
    op.create_index(
        "ix_chunk_embeddings_model_dim",
        "chunk_embeddings",
        ["embedding_model", "embedding_dim"],
        unique=False,
        schema="app",
    )

    for dimension in INDEXED_DIMENSIONS:
        # m=16 / ef_construction=64 are pgvector's defaults and are appropriate
        # for a corpus of this size; the plan revisits them if recall demands it.
        op.execute(
            sa.text(
                f"CREATE INDEX ix_chunk_embeddings_hnsw_{dimension} "
                f"ON app.chunk_embeddings "
                f"USING hnsw ((embedding::halfvec({dimension})) halfvec_cosine_ops) "
                f"WITH (m = 16, ef_construction = 64) "
                f"WHERE embedding_dim = {dimension}"
            )
        )


def downgrade() -> None:
    for dimension in INDEXED_DIMENSIONS:
        op.execute(sa.text(f"DROP INDEX IF EXISTS app.ix_chunk_embeddings_hnsw_{dimension}"))
    op.drop_index("ix_chunk_embeddings_model_dim", table_name="chunk_embeddings", schema="app")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chunk_embeddings", schema="app")
    op.drop_index(
        "ix_document_chunks_tsv", table_name="document_chunks", schema="app", postgresql_using="gin"
    )
    op.drop_index(
        "ix_document_chunks_document_id_chunk_index", table_name="document_chunks", schema="app"
    )
    op.drop_table("document_chunks", schema="app")
    op.drop_index("ix_documents_user_id_created_at", table_name="documents", schema="app")
    op.drop_index("ix_documents_status", table_name="documents", schema="app")
    op.drop_table("documents", schema="app")
    # ### end Alembic commands ###
