"""llm call usage and cost tracking

Revision ID: be3cf5c03cd4
Revises: 5d936a07b145
Created: 2026-08-09 23:57:46.034425
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "be3cf5c03cd4"
down_revision: str | None = "5d936a07b145"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_calls",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_name", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=16), nullable=True),
        sa.Column("prompt_checksum", sa.String(length=32), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("streamed", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SUCCEEDED", "FAILED", name="llm_call_status", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("finish_reason", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["app.conversations.id"],
            name=op.f("fk_llm_calls_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["app.messages.id"],
            name=op.f("fk_llm_calls_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_llm_calls_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
        schema="app",
    )
    op.create_index(
        "ix_llm_calls_created_at", "llm_calls", ["created_at"], unique=False, schema="app"
    )
    op.create_index(
        "ix_llm_calls_provider_model",
        "llm_calls",
        ["provider", "model"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_llm_calls_user_id_created_at",
        "llm_calls",
        ["user_id", "created_at"],
        unique=False,
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_llm_calls_user_id_created_at", table_name="llm_calls", schema="app")
    op.drop_index("ix_llm_calls_provider_model", table_name="llm_calls", schema="app")
    op.drop_index("ix_llm_calls_created_at", table_name="llm_calls", schema="app")
    op.drop_table("llm_calls", schema="app")
    # ### end Alembic commands ###
